# Generated by Django 3.1.5 on 2021-01-21 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Module',
            fields=[
                ('mod_code', models.TextField(blank=True, primary_key=True, serialize=False)),
                ('title', models.TextField(blank=True, null=True)),
                ('year', models.IntegerField(blank=True, null=True)),
                ('department', models.TextField(blank=True, null=True)),
                ('contact_hours', models.IntegerField(blank=True, null=True)),
                ('exams', models.IntegerField(blank=True, null=True)),
                ('practical', models.IntegerField(blank=True, null=True)),
                ('coursework', models.IntegerField(blank=True, null=True)),
                ('credits', models.IntegerField(blank=True, null=True)),
                ('prerequisites', models.TextField(blank=True, null=True)),
                ('summary', models.TextField(blank=True, null=True)),
                ('outcomes', models.TextField(blank=True, null=True)),
                ('status', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
