# Generated by Django 3.1.5 on 2021-01-25 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Module',
            fields=[
                ('mod_code', models.TextField(primary_key=True, serialize=False)),
                ('jacs_code', models.TextField(blank=True, null=True)),
                ('hecos_code', models.TextField(blank=True, null=True)),
                ('title', models.TextField(blank=True, null=True)),
                ('short_title', models.TextField(blank=True, null=True)),
                ('level', models.IntegerField(blank=True, null=True)),
                ('department', models.TextField(blank=True, null=True)),
                ('with_effect_from', models.TextField(blank=True, null=True)),
                ('availability_terms', models.TextField(blank=True, null=True)),
                ('credits', models.IntegerField(blank=True, null=True)),
                ('corequisites', models.TextField(blank=True, null=True)),
                ('prerequisites', models.TextField(blank=True, null=True)),
                ('banned_combinations', models.TextField(blank=True, null=True)),
                ('learning_outcomes', models.TextField(blank=True, null=True)),
                ('summary', models.TextField(blank=True, null=True)),
                ('notional_learning_hours', models.TextField(blank=True, null=True)),
                ('books_to_purchase', models.TextField(blank=True, null=True)),
                ('core_reading', models.TextField(blank=True, null=True)),
                ('exam_format', models.TextField(blank=True, null=True)),
                ('status', models.TextField(blank=True, null=True)),
                ('project', models.BooleanField(blank=True, null=True)),
                ('lab_hours', models.IntegerField(blank=True, null=True)),
                ('deg_progs', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
