# Generated by Django 3.1.7 on 2021-03-24 19:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseLeader',
            fields=[
                ('leader', models.BooleanField()),
                ('term', models.CharField(choices=[('1', 'Term 1'), ('2', 'Term 2'), ('Both', 'Both')], max_length=6)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('mod_code', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('level', models.IntegerField(blank=True, choices=[(4, '4'), (5, '5'), (6, '6'), (7, '7')], null=True)),
                ('credits', models.IntegerField(blank=True, choices=[(-1, '-1'), (15, '15'), (30, '30'), (60, '60')], null=True)),
                ('corequisites', models.TextField(blank=True, max_length=255, null=True)),
                ('prerequisites', models.TextField(blank=True, max_length=255, null=True)),
                ('banned_combinations', models.TextField(blank=True, null=True)),
                ('learning_outcomes', models.TextField(blank=True, null=True)),
                ('core_reading', models.TextField(blank=True, null=True)),
                ('exam_format', models.TextField(blank=True, null=True)),
                ('summary', models.TextField(blank=True, null=True)),
                ('status', models.CharField(blank=True, choices=[('ACTIVE', 'ACTIVE'), ('DORMANT', 'DORMANT'), ('WITHDRAWN', 'WITHDRAWN'), ('WONTRUN', 'WONTRUN')], max_length=15, null=True)),
                ('project', models.BooleanField(blank=True, null=True)),
            ],
            options={
                'ordering': ['mod_code'],
            },
        ),
        migrations.CreateModel(
            name='ModuleSelection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(max_length=20)),
                ('student_name', models.CharField(max_length=255)),
                ('stage', models.IntegerField()),
                ('entry_year', models.CharField(default='2021', max_length=4)),
                ('status', models.CharField(max_length=20)),
                ('date_requested', models.DateTimeField(null=True)),
                ('last_modified', models.DateTimeField(null=True)),
                ('comments', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ModuleVariant',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='OptionalModule',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='OptionRule',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('entry_year', models.CharField(max_length=4)),
                ('stage', models.IntegerField()),
                ('constraint_type', models.CharField(choices=[('CORE', 'Core'), ('OPTS', 'Option'), ('STRAND', 'Strand'), ('DISC_ALT', 'DiscAlt'), ('DISALLOWED', 'Disallowed'), ('CREDITS', 'Credits'), ('MAX_STRAND', 'MaxStrand')], max_length=20)),
                ('min_quantity', models.IntegerField(default=1)),
                ('max_quantity', models.IntegerField(default=1)),
                ('mod_code_pattern', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='People',
            fields=[
                ('id', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Programme',
            fields=[
                ('prog_code', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255, unique=True)),
                ('level', models.CharField(choices=[('BSC', "Bachelor's"), ('MSCI', "Master's")], max_length=10)),
                ('yini', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(max_length=20, null=True)),
                ('entry_year', models.CharField(max_length=4, null=True)),
                ('prog_code', models.CharField(max_length=10, null=True)),
                ('stage', models.SmallIntegerField(null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Strands',
            fields=[
                ('strand', models.CharField(choices=[('AI', 'AI'), ('IS', 'IS'), ('SE', 'SE'), ('DNS', 'DNS')], max_length=5)),
                ('strand_id', models.AutoField(primary_key=True, serialize=False)),
                ('module', models.ForeignKey(db_column='mod_code', on_delete=django.db.models.deletion.CASCADE, to='modulesApplication.module')),
            ],
        ),
        migrations.AddConstraint(
            model_name='programme',
            constraint=models.CheckConstraint(check=models.Q(('level__iexact', 'bsc'), ('level__iexact', 'msci'), _connector='OR'), name='Valid degree level constraint'),
        ),
        migrations.AddField(
            model_name='optionrule',
            name='prog_code',
            field=models.ForeignKey(db_column='prog_code', on_delete=django.db.models.deletion.DO_NOTHING, to='modulesApplication.programme'),
        ),
        migrations.AddField(
            model_name='optionalmodule',
            name='mod_code',
            field=models.ForeignKey(db_column='mod_code', on_delete=django.db.models.deletion.DO_NOTHING, to='modulesApplication.module'),
        ),
        migrations.AddField(
            model_name='optionalmodule',
            name='prog_code',
            field=models.ForeignKey(db_column='prog_code', on_delete=django.db.models.deletion.DO_NOTHING, to='modulesApplication.programme'),
        ),
        migrations.AddField(
            model_name='modulevariant',
            name='major',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='major', to='modulesApplication.module'),
        ),
        migrations.AddField(
            model_name='modulevariant',
            name='minor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='minor', to='modulesApplication.module'),
        ),
        migrations.AddField(
            model_name='moduleselection',
            name='programme',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='modulesApplication.programme'),
        ),
        migrations.AddField(
            model_name='module',
            name='selected_in',
            field=models.ManyToManyField(to='modulesApplication.ModuleSelection'),
        ),
        migrations.AddField(
            model_name='courseleader',
            name='module',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modulesApplication.module'),
        ),
        migrations.AddField(
            model_name='courseleader',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modulesApplication.people'),
        ),
        migrations.AlterUniqueTogether(
            name='strands',
            unique_together={('module', 'strand')},
        ),
        migrations.AlterUniqueTogether(
            name='optionalmodule',
            unique_together={('prog_code', 'mod_code')},
        ),
        migrations.AlterUniqueTogether(
            name='modulevariant',
            unique_together={('major', 'minor')},
        ),
        migrations.AlterUniqueTogether(
            name='courseleader',
            unique_together={('module', 'person')},
        ),
    ]
