# Generated by Django 3.1.5 on 2021-01-25 20:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('modulesApplication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Strands',
            fields=[
                ('mod_code', models.ForeignKey(db_column='mod_code', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='modulesApplication.module')),
                ('strand', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
