# Generated by Django 3.1.5 on 2021-01-24 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulesApplication', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='module',
            name='contact_hours',
        ),
        migrations.RemoveField(
            model_name='module',
            name='coursework',
        ),
        migrations.RemoveField(
            model_name='module',
            name='exams',
        ),
        migrations.RemoveField(
            model_name='module',
            name='outcomes',
        ),
        migrations.RemoveField(
            model_name='module',
            name='practical',
        ),
        migrations.RemoveField(
            model_name='module',
            name='year',
        ),
        migrations.AddField(
            model_name='module',
            name='availability_terms',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='module',
            name='banned_combinations',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='module',
            name='books_to_purchase',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='module',
            name='core_reading',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='module',
            name='corequisites',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='module',
            name='deg_progs',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='module',
            name='exam_format',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='module',
            name='hecos_code',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='module',
            name='jacs_code',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='module',
            name='lab_hours',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='module',
            name='learning_outcomes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='module',
            name='level',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='module',
            name='notional_learning_hours',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='module',
            name='project',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='module',
            name='short_title',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='module',
            name='with_effect_from',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='module',
            name='mod_code',
            field=models.TextField(primary_key=True, serialize=False),
        ),
    ]
