# Generated by Django 3.1.5 on 2021-01-26 10:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('modulesApplication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Strands',
            fields=[
                ('strand_id', models.AutoField(primary_key=True, serialize=False)),
                ('strand', models.TextField()),
                ('mod_code', models.ForeignKey(db_column='mod_code', on_delete=django.db.models.deletion.DO_NOTHING, to='modulesApplication.module')),
            ],
            options={
                'unique_together': {('mod_code', 'strand')},
            },
        ),
    ]
