# Generated by Django 3.1.5 on 2021-01-26 21:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modulesApplication', '0002_strands'),
    ]

    operations = [
        migrations.RenameField(
            model_name='strands',
            old_name='mod_code',
            new_name='module',
        ),
        migrations.AlterUniqueTogether(
            name='strands',
            unique_together={('module', 'strand')},
        ),
    ]
