# Generated by Django 3.1.5 on 2021-01-29 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulesApplication', '0003_auto_20210126_2121'),
    ]

    operations = [
        migrations.CreateModel(
            name='Programme',
            fields=[
                ('prog_code', models.TextField(primary_key=True, serialize=False)),
                ('title', models.TextField()),
                ('level', models.TextField()),
            ],
        ),
    ]
