# Generated by Django 3.1.5 on 2021-02-02 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulesApplication', '0004_programme'),
    ]

    operations = [
        migrations.AddField(
            model_name='programme',
            name='yini',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='programme',
            name='level',
            field=models.TextField(choices=[('BSC', "Bachelor's"), ('MSCI', "Master's")]),
        ),
        migrations.AlterField(
            model_name='programme',
            name='title',
            field=models.TextField(unique=True),
        ),
        migrations.AddConstraint(
            model_name='programme',
            constraint=models.CheckConstraint(check=models.Q(('level__iexact', 'bsc'), ('level__iexact', 'msci'), _connector='OR'), name='Valid degree level constraint'),
        ),
    ]
