# Generated by Django 3.1.5 on 2021-02-03 11:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('modulesApplication', '0005_auto_20210202_2126'),
    ]

    operations = [
        migrations.CreateModel(
            name='OptionRule',
            fields=[
                ('rule_id', models.AutoField(primary_key=True, serialize=False)),
                ('entry_year', models.TextField()),
                ('stage', models.IntegerField()),
                ('constraint_type', models.TextField()),
                ('min_quantity', models.IntegerField(default=1)),
                ('max_quantity', models.IntegerField(default=1)),
                ('mod_code_pattern', models.TextField()),
                ('prog_code', models.ForeignKey(db_column='prog_code', on_delete=django.db.models.deletion.DO_NOTHING, to='modulesApplication.programme')),
            ],
        ),
    ]
