# Generated by Django 3.1.5 on 2021-02-03 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulesApplication', '0006_optionrule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='optionrule',
            name='constraint_type',
            field=models.TextField(choices=[('CORE', 'Core'), ('OPTS', 'Option'), ('STRAND', 'Strand'), ('DISC_ALT', 'DiscAlt'), ('DISALLOWED', 'Disallowed'), ('CREDITS', 'Credits'), ('MAX_STRAND', 'MaxStrand')]),
        ),
    ]
