# Generated by Django 3.1.5 on 2021-02-04 20:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modulesApplication', '0007_auto_20210203_1829'),
    ]

    operations = [
        migrations.RenameField(
            model_name='optionrule',
            old_name='rule_id',
            new_name='id',
        ),
    ]
