# Generated by Django 3.1.5 on 2021-02-09 20:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('modulesApplication', '0008_auto_20210204_2037'),
    ]

    operations = [
        migrations.CreateModel(
            name='OptionalModule',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('mod_code', models.ForeignKey(db_column='mod_code', on_delete=django.db.models.deletion.DO_NOTHING, to='modulesApplication.module')),
                ('prog_code', models.ForeignKey(db_column='prog_code', on_delete=django.db.models.deletion.DO_NOTHING, to='modulesApplication.programme')),
            ],
            options={
                'unique_together': {('prog_code', 'mod_code')},
            },
        ),
    ]
