# Generated by Django 3.1.5 on 2021-02-11 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulesApplication', '0009_optionalmodule'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModuleSelection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.TextField()),
                ('stage', models.IntegerField()),
                ('status', models.TextField()),
            ],
        ),
    ]
