# Generated by Django 3.1.5 on 2021-02-11 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulesApplication', '0010_moduleselection'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='selections',
            field=models.ManyToManyField(to='modulesApplication.ModuleSelection'),
        ),
    ]
