# Generated by Django 3.1.5 on 2021-02-17 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulesApplication', '0011_module_selections'),
    ]

    operations = [
        migrations.CreateModel(
            name='People',
            fields=[
                ('id', models.TextField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('email', models.TextField()),
            ],
        ),
    ]
