# Generated by Django 3.1.5 on 2021-02-17 20:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('modulesApplication', '0012_people'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseLeader',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leader', models.BooleanField()),
                ('term', models.TextField()),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modulesApplication.module')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modulesApplication.people')),
            ],
            options={
                'unique_together': {('module', 'person')},
            },
        ),
    ]
