# Generated by Django 3.1.5 on 2021-02-18 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulesApplication', '0013_courseleader'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseleader',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
