# Generated by Django 3.1.5 on 2021-02-18 11:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('modulesApplication', '0014_auto_20210218_1152'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModuleVariant',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('major', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='major', to='modulesApplication.module')),
                ('minor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='minor', to='modulesApplication.module')),
            ],
            options={
                'unique_together': {('major', 'minor')},
            },
        ),
    ]
