# Generated by Django 3.1.5 on 2021-02-20 22:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modulesApplication', '0015_modulevariant'),
    ]

    operations = [
        migrations.RenameField(
            model_name='module',
            old_name='selections',
            new_name='selected_in',
        ),
    ]
