# Generated by Django 3.1.5 on 2021-02-20 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulesApplication', '0016_auto_20210220_2240'),
    ]

    operations = [
        migrations.AddField(
            model_name='moduleselection',
            name='entry_year',
            field=models.TextField(default='2021'),
        ),
    ]
