# Generated by Django 3.1.5 on 2021-02-20 23:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('modulesApplication', '0017_moduleselection_entry_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='moduleselection',
            name='programme',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='modulesApplication.programme'),
        ),
    ]
