# Generated by Django 3.1.7 on 2021-03-04 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulesApplication', '0018_moduleselection_programme'),
    ]

    operations = [
        migrations.AddField(
            model_name='moduleselection',
            name='date_requested',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='moduleselection',
            name='last_modified',
            field=models.DateTimeField(null=True),
        ),
    ]
