# Generated by Django 3.1.7 on 2021-03-04 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulesApplication', '0019_auto_20210304_2241'),
    ]

    operations = [
        migrations.AddField(
            model_name='moduleselection',
            name='comments',
            field=models.TextField(null=True),
        ),
    ]
