# Generated by Django 3.1.7 on 2021-03-10 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulesApplication', '0020_moduleselection_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='moduleselection',
            name='student_name',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
