# Generated by Django 3.1.7 on 2021-03-18 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulesApplication', '0023_auto_20210316_1800'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseleader',
            name='term',
            field=models.TextField(choices=[('1', 'Term 1'), ('2', 'Term 2'), ('Both', 'Both')]),
        ),
    ]
