# Generated by Django 3.1.7 on 2021-03-18 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modulesApplication', '0024_auto_20210318_1514'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='module',
            options={'ordering': ['mod_code']},
        ),
    ]
