# Generated by Django 3.1.7 on 2021-03-19 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modulesApplication', '0025_auto_20210318_1519'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='module',
            name='availability_terms',
        ),
        migrations.RemoveField(
            model_name='module',
            name='books_to_purchase',
        ),
        migrations.RemoveField(
            model_name='module',
            name='core_reading',
        ),
        migrations.RemoveField(
            model_name='module',
            name='deg_progs',
        ),
        migrations.RemoveField(
            model_name='module',
            name='department',
        ),
        migrations.RemoveField(
            model_name='module',
            name='exam_format',
        ),
        migrations.RemoveField(
            model_name='module',
            name='hecos_code',
        ),
        migrations.RemoveField(
            model_name='module',
            name='jacs_code',
        ),
        migrations.RemoveField(
            model_name='module',
            name='lab_hours',
        ),
        migrations.RemoveField(
            model_name='module',
            name='notional_learning_hours',
        ),
        migrations.RemoveField(
            model_name='module',
            name='short_title',
        ),
        migrations.RemoveField(
            model_name='module',
            name='with_effect_from',
        ),
    ]
