# Generated by Django 3.1.7 on 2021-03-19 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulesApplication', '0026_auto_20210319_1402'),
    ]

    operations = [
        migrations.AlterField(
            model_name='module',
            name='credits',
            field=models.IntegerField(blank=True, choices=[(-1, '-1'), (15, '15'), (30, '30'), (60, '60')], null=True),
        ),
        migrations.AlterField(
            model_name='module',
            name='level',
            field=models.IntegerField(blank=True, choices=[('4', '4'), ('5', '5'), ('6', '6'), ('7', '7')], null=True),
        ),
        migrations.AlterField(
            model_name='module',
            name='status',
            field=models.TextField(blank=True, choices=[('', 'n/a'), ('ACTIVE', 'Active'), ('DORMANT', 'Dormant'), ('WITHDRAWN', 'Withdrawn'), ('WONTRUN', 'Wontrun')], null=True),
        ),
    ]
