# Generated by Django 3.1.7 on 2021-03-19 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulesApplication', '0027_auto_20210319_1447'),
    ]

    operations = [
        migrations.AlterField(
            model_name='module',
            name='level',
            field=models.IntegerField(blank=True, choices=[(4, '4'), (5, '5'), (6, '6'), (7, '7')], null=True),
        ),
        migrations.AlterField(
            model_name='module',
            name='mod_code',
            field=models.TextField(primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='module',
            name='status',
            field=models.TextField(blank=True, choices=[('ACTIVE', 'ACTIVE'), ('DORMANT', 'DORMANT'), ('WITHDRAWN', 'WITHDRAWN'), ('WONTRUN', 'WONTRUN')], null=True),
        ),
    ]
