# Generated by Django 3.1.7 on 2021-03-19 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulesApplication', '0028_auto_20210319_1507'),
    ]

    operations = [
        migrations.AlterField(
            model_name='module',
            name='mod_code',
            field=models.TextField(primary_key=True, serialize=False),
        ),
    ]
