# Generated by Django 3.1.7 on 2021-03-19 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modulesApplication', '0030_auto_20210319_1535'),
    ]

    operations = [
        migrations.RenameField(
            model_name='module',
            old_name='recommended_reading',
            new_name='core_reading',
        ),
    ]
