# Generated by Django 3.1.7 on 2021-03-21 14:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('modulesApplication', '0031_auto_20210319_1536'),
    ]

    operations = [
        migrations.AlterField(
            model_name='strands',
            name='module',
            field=models.ForeignKey(db_column='mod_code', on_delete=django.db.models.deletion.CASCADE, to='modulesApplication.module'),
        ),
        migrations.AlterField(
            model_name='strands',
            name='strand',
            field=models.TextField(choices=[('AI', 'AI'), ('IS', 'IS'), ('SE', 'SE'), ('DNS', 'DNS')]),
        ),
    ]
