# Generated by Django 3.1.7 on 2021-03-23 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulesApplication', '0032_auto_20210321_1459'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseleader',
            name='term',
            field=models.CharField(choices=[('1', 'Term 1'), ('2', 'Term 2'), ('Both', 'Both')], max_length=6),
        ),
        migrations.AlterField(
            model_name='module',
            name='corequisites',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='module',
            name='mod_code',
            field=models.CharField(max_length=10, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='module',
            name='prerequisites',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='module',
            name='status',
            field=models.CharField(blank=True, choices=[('ACTIVE', 'ACTIVE'), ('DORMANT', 'DORMANT'), ('WITHDRAWN', 'WITHDRAWN'), ('WONTRUN', 'WONTRUN')], max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='module',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='moduleselection',
            name='entry_year',
            field=models.CharField(default='2021', max_length=4),
        ),
        migrations.AlterField(
            model_name='moduleselection',
            name='status',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='moduleselection',
            name='student_id',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='moduleselection',
            name='student_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='optionrule',
            name='constraint_type',
            field=models.CharField(choices=[('CORE', 'Core'), ('OPTS', 'Option'), ('STRAND', 'Strand'), ('DISC_ALT', 'DiscAlt'), ('DISALLOWED', 'Disallowed'), ('CREDITS', 'Credits'), ('MAX_STRAND', 'MaxStrand')], max_length=20),
        ),
        migrations.AlterField(
            model_name='optionrule',
            name='entry_year',
            field=models.CharField(max_length=4),
        ),
        migrations.AlterField(
            model_name='optionrule',
            name='mod_code_pattern',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='people',
            name='email',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='people',
            name='id',
            field=models.CharField(max_length=5, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='people',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='programme',
            name='level',
            field=models.CharField(choices=[('BSC', "Bachelor's"), ('MSCI', "Master's")], max_length=10),
        ),
        migrations.AlterField(
            model_name='programme',
            name='prog_code',
            field=models.CharField(max_length=10, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='programme',
            name='title',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='strands',
            name='strand',
            field=models.CharField(choices=[('AI', 'AI'), ('IS', 'IS'), ('SE', 'SE'), ('DNS', 'DNS')], max_length=5),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='entry_year',
            field=models.CharField(max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='prog_code',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='student_id',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
