# Generated by Django 3.1.7 on 2021-03-23 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulesApplication', '0033_auto_20210323_2112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='optionrule',
            name='mod_code_pattern',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='programme',
            name='prog_code',
            field=models.CharField(max_length=255, primary_key=True, serialize=False),
        ),
    ]
