from django.db import models


class ModuleVariant(models.Model):
    """
    A class to map modules to their variants, e.g., CS2815 is a variant of CS2810.
    """
    major = models.ForeignKey('Module', models.CASCADE, related_name="major")
    """Foreign key to the major module - e.g. CS2810 is the major variant of CS2815."""
    minor = models.ForeignKey('Module', models.CASCADE,
                              related_name="minor")
    """Foreign key to the minor module - e.g. CS2815 is a variant of CS2810."""
    id = models.AutoField(primary_key=True)
    """Autogenerated ID in lieue of composite key. A `unique_together` constraint is defined in the Meta inner class
    (see source code) between the major/minor modules."""

    class Meta:
        unique_together = ('major', 'minor')  # The "composite key" though not supported in Django
