"""Contains various settings and some default Django files for this project.

Most of this is automatically generated by Django or our own configuration of various settings. Nothing very much
interesting to see here.
"""
